scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
